AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  LambdaCopySourceBucketToDestinationBucket:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs16.x
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::351562031848:role/Lambda-site-access-role'
      Environment:
        Variables:
          dest_bucket: destination-images-bucket-zszek
          source_bucket: source-image-bucket-zszek
